default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: freelance_camp_documents/development   # name this whatever you want
  host: localhost
  pool: 5                             # Not required
  timeout: 5000                       # Not required

test:
  adapter: postgresql
  database: freelance_camp_documents/test   # name this whatever you want
  host: localhost
  pool: 5                             # Not required
  timeout: 5000                       # Not required

production:
  adapter: postgresql
  database: freelance_camp_documents/production   # name this whatever you want
  host: localhost
  pool: 5                             # Not required
  timeout: 5000
